sudo: required
services:
    - docker
before_install:
  - echo "everything is ok"

before_deploy:
  - docker build -t my-static-website .
  
script:
  - echo "everything is ok"

#Run our deployment container via shell script if commiting to the master branch
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: master
