sudo: required
services:
  - docker

script:
  - docker build -t reactapp .
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "reactapp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-440283140762"
  bucket_path: "reactapp"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
