sudo: required
services:
    - docker
script:
  - echo "everything is working fine"
before_deploy:
  - docker build -t myreact-cicd .

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: master
