
sudo: required
services:
    - docker
before_install:
  - docker build -t myreact-cicd .

script:
  - echo "everything working fine"

before_deploy:
  - docker build -t myreact-cicd .

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: main
