sudo: required
services:
  - docker

before_deploy: "echo 'ready?'"

script:
- echo "skipping tests"


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "my-cicd-react"
  skip_cleanup: true
  region: "us-east-1"
  
  on:
    branch: main
