sudo: required
services:
    - docker
before_install:
  - docker build -t myreact-cicd .

script:
  - echo "everything is working"
  
deploy:
  skip_cleanup: true
  provider: script
  on:
    branch: main
