sudo: required
services:
  - docker


script:
  - docker build -t reactapp .

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "reactapp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-440283140762"
  bucket_path: "reactapp"
  on:
    branch: main
