version: 2.1
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: node:16.16.0-alpine
    steps:
      - checkout
      - run:
          name: build docker file
          command: docker build -t rohitmarathe/todo .
      - run:
          name: run docker file
          command: docker run -p 3000:3000 -t rohitmarathe/todo
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./dist/ s3://myreact-cicd 





